site_icon = "🐻"
site_name = "My Website"
author = "Your Name"
output_dir = "mdbear"
language = "en"  # "en" for English, "zh" for Chinese

[[nav]]
name = "Home"
path = "index.md"
type = "page"

[[nav]]
name = "Blog"
path = "blog.html"
type = "page"

[[nav]]
name = "About"
path = "about.md"
type = "page"
